# Generated by Django 4.2.3 on 2023-07-06 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('elevator_name', models.CharField(blank=True, max_length=20, null=True)),
                ('elevator_number', models.IntegerField(blank=True)),
                ('last_floor', models.IntegerField(blank=True, null=True)),
                ('moving_status', models.CharField(blank=True, choices=[('U', 'Moving Up'), ('D', 'Moving Down'), ('S', 'Still')], default='S', max_length=1, null=True)),
                ('door_status', models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Class')], default='C', max_length=1, null=True)),
                ('status_light', models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green')], default='G', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevator.elevator')),
                ('floor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevator.floor')),
            ],
        ),
    ]
