# Generated by Django 4.2.3 on 2023-07-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_rename_last_floor_elevator_reached_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevatorrequest',
            name='floor',
        ),
        migrations.AddField(
            model_name='elevatorrequest',
            name='destination_floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='elevator.floor'),
        ),
        migrations.AddField(
            model_name='elevatorrequest',
            name='requested_floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevator.floor'),
        ),
    ]
